### ISSUE TITLE
Action doesn't run on every PR

### ISSUE THREAD

**Issue by michaelflores-italic** [OskarAhl/Lighthouse-github-action#7]
I'm noticing that sometimes the Action doesn't attempt to run on a PR, even though Vercel had deployed the PR. When I look under the repo's actions tab, I can see that it wasn't that the Action failed but that the action was never triggered for the PR. It should trigger due to a Vercel comment right?

**Comment by flexbox** [comment]
Hey @michaelflores-italic 

If you want to run it on every PR you should change this

```yml
name: Vercel Preview URL Lighthouse Audit

on:
  issue_comment:
    types: [edited]
```

to

```yml
name: Vercel Preview URL Lighthouse Audit

on: [pull_request]
```

or you can select the branch you want

```yml
name: Vercel Preview URL Lighthouse Audit

on:
  push:
    branches:
      - main
```
